name: card_docker
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.16.0+1
  cupertino_icons: ^1.0.0
  equatable: ^1.2.6
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  flutter_bloc: ^6.1.2
  google_sign_in: ^4.5.9



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/
